### ISSUE TITLE
Comparison to repository 

### ISSUE THREAD

**Issue by kaszperro** [Fdhvdu/ThreadPool#1]
Could you add comparison to this repository: https://github.com/Tyler-Hardin/thread_pool?
I want to choose between yours and that.

**Comment by Fdhvdu** [comment]
Sure.

**Comment by kaszperro** [comment]
Thanks :)

**Comment by Fdhvdu** [comment]
Hello, I get some compilation errors. I will fix it later.
However, after reviewing the code, I guess it will not faster than mine and progschj's ThreadPool.
(I mean thread_pool here instead of priority_thread_pool.)
(I think Tyler-Hardin's thread_pool is a complex version of progschj's ThreadPool.)
So my advice is, if you want your jobs can be scheduled in priority mode, use Tyler-Hardin's thread_pool.
If not, use mine or progschj's ThreadPool.
**But as mentioned before, it just my guessing.**
If you want a fair evaluation, I will show it quickly.

**Comment by kaszperro** [comment]
I've applied your solution to my code. I've got to say - it's faster than Tyler-Hardin's.
Thanks

**Comment by Fdhvdu** [comment]
Done
Check https://github.com/Fdhvdu/ThreadPool/blob/master/comparison/README.md#result
